# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-states-415352219645"
    dynamodb_table = "terraform-locks-415352219645"
    encrypt        = true
    key            = "polkadot/api/aws/kusama/dev/global/./terraform.tfstate"
    region         = "us-east-1"
  }
}
